name: CI

on: push
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  build:
    strategy:
      matrix:
        kind: ['linux', 'windows']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
            config: Release
          - kind: windows
            os: windows-latest
            target: win10-x64
            config: ReleaseWindows
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
          
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build -c ${{ matrix.config }} --no-restore
        
      - name: Test
        run: dotnet test -c ${{ matrix.config }} --no-build
      
      - name: Version
        shell: bash
        run: |
          echo "::set-output name=version-prefix::$(grep -oPm1 "(?<=<VersionPrefix>)[^<]+" src/Directory.Build.props)"
          echo "::set-output name=version-suffix::$(echo "ci$GITHUB_RUN_ID")"
          
      - name: Publish Windows
        if: ${{ matrix.target == 'win10-x64' }}
        shell: bash
        run: |
          target="${{ matrix.target }}"
          version="${{ steps.version.outputs.version-prefix }}-${{ steps.version.outputs.version-suffix }}"
          release_name="min-ed-launcher_$version_$target"
          dotnet publish src\MinEdLauncher\MinEdLauncher.fsproj -r "$target" --self-contained true -o "artifacts\$release_name" -c ${{ matrix.config }} -p:PublishSingleFile=true -p:VersionSuffix=${{ steps.version.outputs.version-suffix }}
          dotnet publish src\MinEdLauncher.Bootstrap\MinEdLauncher.Bootstrap.csproj -r "$target" --self-contained true -o "artifacts\$release_name" -c ${{ matrix.config }} -p:VersionSuffix=${{ steps.version.outputs.version-suffix }}
        
      - name: Publish Linux
        if: ${{ matrix.target == 'linux-x64' }}
        run: |
          target="${{ matrix.target }}"
          version="${{ steps.version.outputs.version-prefix }}-${{ steps.version.outputs.version-suffix }}"
          release_name="min-ed-launcher_$version_$target"
          dotnet publish src/MinEdLauncher/MinEdLauncher.fsproj -r "$target" --self-contained true -o "artifacts/$release_name" -c ${{ matrix.config }} -p:PublishSingleFile=true -p:VersionSuffix=${{ steps.version.outputs.version-suffix }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: "artifacts/"